[package]
name = "spotify-now-playing"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
askama = "0.8.0"
include_dir = "0.2.1"
log = "0.4.7"
simple_logger = "1.3.0"
